#pragma once
#include "common.h"

typedef enum _CM_VALIDATION
{
    CM_VALIDATION_OK = 0,
    CM_INVALID_USERNAME,
    CM_INVALID_PASSWORD,
    CM_WEAK_PASSWORD,
    CM_USER_ALREADY_EXISTS,
    CM_USER_ALREADY_LOGGED_IN,
    CM_CLIENT_ALREADY_LOGGED_IN,
    CM_CLIENT_NOT_LOGGED_IN
}CM_VALIDATION, *PCM_VALIDATION;


CM_VALIDATION ValidateUsernamePassword(TCHAR* Username, TCHAR* Password);